In [1]:
ROOT_PATH = 'C:/Users/khoan/OneDrive/Documents/stock_data_scraper'
import os
os.chdir(ROOT_PATH)

In [2]:
%load_ext autoreload
%autoreload 2

In [3]:
from utils.generic_utils import SQLModule
import pandas as pd
import plotly.graph_objects as go
from plotly.subplots import make_subplots

In [4]:
engine = SQLModule.get_engine(country = 'australia')

In [5]:
# Collect from 'company_section.ipynb'
SECTOR = 'Consumer Defensive'
INDUSTRY = 'Farm Products'

In [6]:
# Get distribution of metrics of company within the industry
query = f"""
    SELECT
        company_name,
        stock_code,
        fundamental,
        fundamental->>'industry' AS industry,
        fundamental->>'marketCap' AS market_cap,
        fundamental->>'priceToBook' AS pb_ratio,
        fundamental->>'profitMargins' AS profit_margins,
        fundamental->>'trailingEps' AS earning_per_share,
        fundamental->>'enterpriseToEbitda' AS evebitda,
        fundamental->>'trailingPegRatio' AS peg_ratio,
        fundamental->>'debtToEquity' AS de_ratio
    FROM stock_info
    WHERE
        fundamental->>'sector' = '{SECTOR}'
        AND
        fundamental->>'industry' = '{INDUSTRY}'
"""
df = pd.read_sql_query(query, engine)
df

,company_name,stock_code,fundamental,industry,market_cap,pb_ratio,profit_margins,earning_per_share,evebitda,peg_ratio,de_ratio
0,Australian Agricultural Company Ltd,AAC,"{'address1': 'Gasworks Plaza', 'address2': 'To...",Farm Products,849901440,0.5601907,-0.28149,0.06,-6.208,None,31.545
1,Duxton Broadacre Farms Ltd,DBF,"{'address1': 'Duxton House', 'address2': '7 Po...",Farm Products,57620220,0.48746517,0.21569,0.12,196.585,None,36.002
2,Clean Seas Seafood Ltd,CSS,"{'address1': '7 Frederick Road', 'city': 'Roya...",Farm Products,18319482,0.29545453,-0.48624,-0.18,-1.076,None,23.604
3,Farm Pride Foods Ltd,FRM,"{'address1': '551 Chandler Road', 'city': 'Key...",Farm Products,39581280,9.000001,-0.02416,-0.02,-46.736,None,1533.239
4,Murray Cod Australia Ltd,MCA,"{'address1': '2 – 4 Lasscock Road', 'city': 'G...",Farm Products,14279491,1.5697675,-0.58823,-0.08,-419.139,None,34.126
5,New Zealand King Salmon Co Ltd,NZK,"{'address1': '17 Bullen Street', 'address2': '...",Farm Products,111835904,0.5694444,0.120790005,0.04,2.626,None,4.918
6,Rare Foods Australia Ltd,RFA,"{'address1': 'Lot 331 Augusta Boat Harbour', '...",Farm Products,6255609,0.6571429,-0.79837,-0.02,-2.317,None,24.271
7,Silver Mines Ltd,SVL,"{'address1': '88 Phillip Street', 'address2': ...",Farm Products,147721360,0.90109897,None,None,-39.206,None,None
8,Australian Agri Projects,AAP,"{'address1': '456 St Kilda Road', 'address2': ...",Farm Products,15481368,1.235294,0.26540002,None,10.809,None,53.751
9,East 33 Ltd,E33,"{'address1': '12 Point Road', 'city': 'Tuncurr...",Farm Products,17093098,0.68749994,-0.50328,-0.02,-7.324,None,60.844
10,Elders Ltd,ELD,"{'address1': '80 Grenfell Street', 'address2':...",Farm Products,1375124224,1.3687997,0.02115,0.28,15.499,None,74.922
11,Inghams Group Ltd,ING,"{'address1': '1 Julius Avenue', 'address2': 'L...",Farm Products,1193092864,5.431472,0.03112,0.27,10.0,None,785.747
12,Graincorp Ltd,GNC,"{'address1': 'International Towers, Tower 2', ...",Farm Products,1643599872,1.0970715,0.00927,0.28,6.933,None,62.554
13,Namoi Cotton Co-Operative Ltd,NAM,"{'address1': '259 Ruthven Street', 'city': 'To...",Farm Products,159506272,1.1015737,0.056989998,0.03,8.684,None,21.772
14,Lynch Group Holdings Ltd,LGL,"{'address1': '8b Williamson Road', 'city': 'In...",Farm Products,207512208,1.0435851,-0.0655,-0.21,7.962,None,50.169
15,Seafarms Group Ltd,SFG,"{'address1': '66 Smith Street', 'address2': 'L...",Farm Products,9673200,0.6666667,-0.7571,None,-1.246,None,66.933
16,Ricegrowers Limited,SGLLV,"{'address1': 'Governor Macquarie Tower', 'addr...",Farm Products,687049344,1.1838424,0.0336,0.96,6.698,None,42.528
17,Wingara AG Ltd,WNR,"{'address1': '50 Ironstone Road', 'address2': ...",Farm Products,1053258,0.54545456,-1.0527999,-0.01,0.234,None,31.769

In [ ]:
# Distribution of market cap
fig = go.Figure()
fig.add_trace(
    go.Histogram(x = df['market_cap'].apply(lambda x : int(x)))
)
fig.update_yaxes(showgrid = True, gridcolor = 'gray', title = 'Number of company')
fig.update_xaxes(title = f'Market capital of company in sector "{SECTOR}" and industry "{INDUSTRY}"')
fig.update_layout(
    width = 1000,
    height = 500,
    plot_bgcolor = 'white',
    paper_bgcolor = 'white',
    font = dict(family = 'Lato', size = 20)
)
fig.show()

:

In [9]:
# Distribution of market cap
fig = go.Figure()
fig.add_trace(
    go.Histogram(x = df['pb_ratio'].apply(lambda x : float(x) if not pd.isna(x) else None))
)
fig.update_yaxes(showgrid = True, gridcolor = 'gray', title = 'Number of company')
fig.update_xaxes(title = f'P/B ratio of company in sector "{SECTOR}" and industry "{INDUSTRY}"')
fig.update_layout(
    width = 1000,
    height = 500,
    plot_bgcolor = 'white',
    paper_bgcolor = 'white',
    font = dict(family = 'Lato', size = 20)
)
fig.show()

In [10]:
# Distribution of market cap
fig = go.Figure()
fig.add_trace(
    go.Histogram(x = df['profit_margins'].apply(lambda x : float(x) if not pd.isna(x) else None))
)
fig.update_yaxes(showgrid = True, gridcolor = 'gray', title = 'Number of company')
fig.update_xaxes(title = f'Profit margin of company in sector "{SECTOR}" and industry "{INDUSTRY}"')
fig.update_layout(
    width = 1000,
    height = 500,
    plot_bgcolor = 'white',
    paper_bgcolor = 'white',
    font = dict(family = 'Lato', size = 20)
)
fig.show()

In [11]:
# Distribution of market cap
fig = go.Figure()
fig.add_trace(
    go.Histogram(x = df['earning_per_share'].apply(lambda x : float(x) if not pd.isna(x) else None))
)
fig.update_yaxes(showgrid = True, gridcolor = 'gray', title = 'Number of company')
fig.update_xaxes(title = f'EPS of company in sector "{SECTOR}" and industry "{INDUSTRY}"')
fig.update_layout(
    width = 1000,
    height = 500,
    plot_bgcolor = 'white',
    paper_bgcolor = 'white',
    font = dict(family = 'Lato', size = 20)
)
fig.show()

In [12]:
# Distribution of market cap
fig = go.Figure()
fig.add_trace(
    go.Histogram(x = df['evebitda'].apply(lambda x : float(x) if not pd.isna(x) else None))
)
fig.update_yaxes(showgrid = True, gridcolor = 'gray', title = 'Number of company')
fig.update_xaxes(title = f'EV/EBITDA of company in sector "{SECTOR}" and industry "{INDUSTRY}"')
fig.update_layout(
    width = 1000,
    height = 500,
    plot_bgcolor = 'white',
    paper_bgcolor = 'white',
    font = dict(family = 'Lato', size = 20)
)
fig.show()

In [13]:
# Distribution of market cap
fig = go.Figure()
fig.add_trace(
    go.Histogram(x = df['peg_ratio'].apply(lambda x : float(x) if not pd.isna(x) else None))
)
fig.update_yaxes(showgrid = True, gridcolor = 'gray', title = 'Number of company')
fig.update_xaxes(title = f'PEG ratio of company in sector "{SECTOR}" and industry "{INDUSTRY}"')
fig.update_layout(
    width = 1000,
    height = 500,
    plot_bgcolor = 'white',
    paper_bgcolor = 'white',
    font = dict(family = 'Lato', size = 20)
)
fig.show()

In [14]:
# Distribution of market cap
fig = go.Figure()
fig.add_trace(
    go.Histogram(x = df['de_ratio'].apply(lambda x : float(x) if not pd.isna(x) else None))
)
fig.update_yaxes(showgrid = True, gridcolor = 'gray', title = 'Number of company')
fig.update_xaxes(title = f'DE ratio of company in sector "{SECTOR}" and industry "{INDUSTRY}"')
fig.update_layout(
    width = 1000,
    height = 500,
    plot_bgcolor = 'white',
    paper_bgcolor = 'white',
    font = dict(family = 'Lato', size = 20)
)
fig.show()

In [17]:
# Screen companies by metrics
query = f"""
    SELECT
        company_name,
        stock_code,
        fundamental->>'industry' AS industry,
        
        fundamental->>'marketCap' AS market_cap,
        fundamental->>'priceToBook' AS pb_ratio,
        fundamental->>'profitMargins' AS profit_margins,
        fundamental->>'trailingEps' AS earning_per_share,
        fundamental->>'enterpriseToEbitda' AS evebitda,
        fundamental->>'trailingPegRatio' AS peg_ratio,
        fundamental->>'debtToEquity' AS de_ratio
    FROM stock_info
    WHERE
        fundamental->>'sector' = '{SECTOR}'
        AND
        fundamental->>'industry' = '{INDUSTRY}'
        
"""
screen = pd.read_sql_query(query, engine).set_index('stock_code')
screen

,company_name,industry,market_cap,pb_ratio,profit_margins,earning_per_share,evebitda,peg_ratio,de_ratio
stock_code,,,,,,,,,
AAC,Australian Agricultural Company Ltd,Farm Products,849901440,0.5601907,-0.28149,0.06,-6.208,None,31.545
DBF,Duxton Broadacre Farms Ltd,Farm Products,57620220,0.48746517,0.21569,0.12,196.585,None,36.002
CSS,Clean Seas Seafood Ltd,Farm Products,18319482,0.29545453,-0.48624,-0.18,-1.076,None,23.604
FRM,Farm Pride Foods Ltd,Farm Products,39581280,9.000001,-0.02416,-0.02,-46.736,None,1533.239
MCA,Murray Cod Australia Ltd,Farm Products,14279491,1.5697675,-0.58823,-0.08,-419.139,None,34.126
NZK,New Zealand King Salmon Co Ltd,Farm Products,111835904,0.5694444,0.120790005,0.04,2.626,None,4.918
RFA,Rare Foods Australia Ltd,Farm Products,6255609,0.6571429,-0.79837,-0.02,-2.317,None,24.271
SVL,Silver Mines Ltd,Farm Products,147721360,0.90109897,None,None,-39.206,None,None
AAP,Australian Agri Projects,Farm Products,15481368,1.235294,0.26540002,None,10.809,None,53.751
E33,East 33 Ltd,Farm Products,17093098,0.68749994,-0.50328,-0.02,-7.324,None,60.844
ELD,Elders Ltd,Farm Products,1375124224,1.3687997,0.02115,0.28,15.499,None,74.922
ING,Inghams Group Ltd,Farm Products,1193092864,5.431472,0.03112,0.27,10.0,None,785.747
GNC,Graincorp Ltd,Farm Products,1643599872,1.0970715,0.00927,0.28,6.933,None,62.554
NAM,Namoi Cotton Co-Operative Ltd,Farm Products,159506272,1.1015737,0.056989998,0.03,8.684,None,21.772
LGL,Lynch Group Holdings Ltd,Farm Products,207512208,1.0435851,-0.0655,-0.21,7.962,None,50.169
SFG,Seafarms Group Ltd,Farm Products,9673200,0.6666667,-0.7571,None,-1.246,None,66.933
SGLLV,Ricegrowers Limited,Farm Products,687049344,1.1838424,0.0336,0.96,6.698,None,42.528
WNR,Wingara AG Ltd,Farm Products,1053258,0.54545456,-1.0527999,-0.01,0.234,None,31.769

In [18]:
the_company = screen.loc['NZK']
the_company

company_name         New Zealand King Salmon Co Ltd
industry                              Farm Products
market_cap                                111835904
pb_ratio                                  0.5694444
profit_margins                          0.120790005
earning_per_share                              0.04
evebitda                                      2.626
peg_ratio                                      None
de_ratio                                      4.918
Name: NZK, dtype: object

In [ ]:
# Rerun the histogram, but add the company in it
fig = make_subplots(rows = 4, cols = 2)
metrics = ['market_cap', 'pb_ratio', 'profit_margins', 'earning_per_share', 'evebitda', 'peg_ratio', 'de_ratio']

for i,metric in enumerate(metrics):
    fig.add_trace(
        go.Histogram(
            x = df[metric].apply(lambda x : float(x) if not pd.isna(x) else None), 
            marker = dict(color = 'blue'),
            showlegend = False
        ),
        row = (i // 2) + 1, col = (i % 2) + 1
    )
    fig.update_xaxes(title = metric, row = (i // 2) + 1, col = (i % 2) + 1)
fig.update_yaxes(showgrid = True, gridcolor = 'gray', title = 'Number of company')

fig.update_layout(
    width = 1000,
    height = 1000,
    plot_bgcolor = 'white',
    paper_bgcolor = 'white',
    font = dict(family = 'Lato', size = 18)
)
fig_full = fig.full_figure_for_development()
for i,metric in enumerate(metrics):
    y_range = fig_full['layout'][f'yaxis{i + 1 if i > 0 else ""}']['range']
    if the_company[metric] is not None:
        fig.add_shape(
            type="line",
            x0 = the_company[metric], x1 = the_company[metric],  # X-position for the vertical line
            y0 = 0, y1 = y_range[1],      # Scaled Y-position (relative to subplot)
            line=dict(color="red", width=2),
            row = (i // 2) + 1, col = (i % 2) + 1
        )
fig.show()

c:\Users\khoan\miniconda3\envs\stock\lib\site-packages\plotly\io\_kaleido.py:338: UserWarning:

full_figure_for_development is not recommended or necessary for production use in most circumstances.
To suppress this warning, set warn=False

In [20]:
# Repeat the analysis but within the sector now

c:\Users\khoan\miniconda3\envs\stock\lib\site-packages\plotly\io\_kaleido.py:338: UserWarning:

full_figure_for_development is not recommended or necessary for production use in most circumstances.
To suppress this warning, set warn=False